### PR TITLE
Python 3 support

### PR DESCRIPTION
**Pull request by cdeil**
@ericmandel – Could you please make `pyjs9` work on Python 3?
(Currently `python setup.py install` fails with a `SyntaxError`.)

### CODE REVIEW

**Comment by ericmandel** [comment]
@cdeil  @taldcroft Any chance I can get some help on this from the python community? I'd like pyjs9 to work everywhere, but I don't know anything about python3.

If no one steps forward, then of course I'll do it, but it will take me longer than it would for someone in the know ...

**Comment by cdeil** [comment]
I'll try and fix trivial Python 3 stuff now and attach a commit here.

**Comment by cdeil** [comment]
@ericmandel – Could you please go to https://travis-ci.org and activate travis-ci for this repo?

I will then add a `.travis.yml` file so that `python setup.py install` is run for Python 2 and 3 for every commit to `master`. Later maybe we can add tests that cover the code, but it's good to activate this early to make sure once things work on Python 2 and 3 it stays that way.

**Comment by cdeil** [comment]
For Python 2 / 3 compatibility I'll use [six](https://pypi.python.org/pypi/six).
It's what Astropy and many other Python packages use.

@ericmandel Do you want me to declare this as a dependency of `pyjs9` in `setup.py` or should I bundle it as a single file `pyjs9/extern/six.py`?

My suggestion would be to bundle it ... it spares you from having to explain this dependency to users at pretty much zero cost (a few kilo-bytes extra).

**Comment by cdeil** [comment]
With the attached changes `python setup.py install` now works with Python 2 and 3.
But I haven't done any tests.

@ericmandel – Do you want to review this now or let it sit for a while until `pyjs9` grows some unit tests?

**Comment by ericmandel** [comment]
@cdeil I've activated travis-ci for pyjs9, as requested. 

I'm going to rely on your expertise to decide how to deal with python-specific issues and techniques.  My main aim is to write a really fantastic Web-based image display, and while the python connection is really important for that effort, it's one step beyond what I can deal with myself. I really appreciate your help.

If your changes make it work on both python 2 and 3, I don't see any reason not to review now, do you?

**Comment by cdeil** [comment]
OK ... hold off reviewing or merging this though ... I'm running into a few Python 3 issues while playing with `pyjs9` for the first time. It should work on Python 3 soon and remain identical on Python 2.

**Comment by cdeil** [comment]
@ericmandel – Thanks for activating travis-ci. Here's the first build:
https://travis-ci.org/ericmandel/pyjs9/builds/52646895

**Comment by ericmandel** [comment]
These changes look fine to my non-expert eye. I'll merge them if you are ready.

File: pyjs9/__init__.py [hunk 1]
```diff
@@ -225,17 +231,17 @@ def send(self, obj, msg='msg'):
...
         'OK'
         """
-        if obj == None:
+        if obj is None:
             obj = {}
         obj['id'] = self.id
         jstr = json.dumps(obj)
         try:
-            url = urllib.urlopen(self.host + '/' + msg, jstr)
+            url = urlopen(self.host + '/' + msg, jstr.encode('utf8'))
```
Comment (cdeil) [inline pyjs9/__init__.py:239]: @ericmandel – Currently this doesn't work ... I get this error in Python 2 and 3:

```
urllib.error.HTTPError: HTTP Error 400: unknown command in POST request: image
```

(In Python 2 it's hidden a bit because of your try .. catch)

I can reproduce the issue like this:

```
import six
six.moves.urllib.request.urlopen('http://localhost:2718/image')
```

This works in Python 2:

```
>>> import urllib
>>> r = urlopen('http://localhost:2718/image')
>>> r.code
400
```

So apparently `six.moves.urllib.request.urlopen` calls `urllib2.urlopen` on Python 2, which raises a `HTTPError` for a 400 return code, whereas `urllib.urlopen` didn't.

I'm not sure what to do here because I'm not familiar with the code. Catch and ignore the HTTPError? Call some other test URL?

**Comment by cdeil** [comment]
I've added a test on travis-ci ... it now shows the same error I see locally:
https://travis-ci.org/ericmandel/pyjs9/jobs/52654958#L1478

File: pyjs9/__init__.py (hunk 1 above)
Comment (ericmandel) [inline pyjs9/__init__.py:239]: Let me look into this. The request is a little more complicated than a request to an ordinary Web server: it's being fielded by the http handler of the node server code. It may be that I have to make a change on that side.

Comment (cdeil) [inline pyjs9/__init__.py:239]: PS, in case you didn't know, the Python standard library HTTP packages are pretty bad and most projects (e.g. [astroquery](http://astroquery.readthedocs.org/en/latest/)) use the third-party [requests package](http://docs.python-requests.org/en/latest/) instead. If you need to do testing from Python you should use `requests` to simplify your life ... for `pyjs9` I guess the HTTP requests are simple enough for now that it's not needed, but it also wouldn't be hard to use it as a dependency or copy some files in `pyjs9/extern` to have it bundled and avoid an extra dependency.

Comment (ericmandel) [inline pyjs9/__init__.py:239]: Duh, this is a bug:

```
def _alive(self):
    """
    An internal routine to send a test message to the helper
    """
    self.send(None, msg="image")
```

The msg value should be “alive”, not “image”:

```
    self.send(None, msg=“alive”)
```

I’ll let you change it in your code and test the fix.

**Comment by ericmandel** [comment]
Regarding use of urllib (or urllib2): this is a temp solution, because last time I checked, python did not support socket.io 1.x (it had some primitive support for v0.9 at one point). So I was forced to find another mechanism, which I isolated in the send() method. I'm still hoping for python support for socket.io, which should allow us to pass even mouse events back to python for more interactive response.

But in the meantime, I am open to using something better. Requests looks great, but the main problem is that I do not know how to package 3rd party code into pyjs9 simply. I can look into this when I get a chance (or, if its trivial and you want to do it ...)

**Comment by cdeil** [comment]
Bundling `requests` is simple: copy everything in the [requests folder in the requests repo](https://github.com/kennethreitz/requests/tree/master/requests) to `pyjs9/extern/requests`. But I just saw that it's 1 MB because it contains some data files, so I won't do this for now.

I tried to add tests in `pyjs9/tests/test_pyjs9.py` that start `js9` via a `pytest` fixture, but I don't know what I'm doing here and it doesn't work for now.

@ericmandel – I think sending numpy arrays for display doesn't work at the moment, so my suggestion would be to not merge this for now, unless you have time for manual testing or continuing with this. I can probably work on this some more next weekend.

**Comment by ericmandel** [comment]
Can you give me a hint about the problem with numpy arrays? If it's a bug in both python 2 and 3, I'll look to fix it this week. If it's only in python 3 or is the result of a change you made, I'll wait for you to look at it. The code should be pretty similar to the pyds9 code, but  again, I am not an expert in this arena and might not have tested many aspects of numpy.

**Comment by cdeil** [comment]
Actually I can't get `js9` to work with Python 2.7 with both this branch and the master branch (i.e. no changes).
Trying the commands from the README I don't get the expected response:

```
>>> js9.SetColormap('red')
None
>>> js9.GetColormap('red')
None
>>> js9.cmap()
''
>>> js9.GetFITS()
>>> js9.GetFITS()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.py", line 266, in GetFITS
    arr = _im2np(im)
  File "/Users/deil/Library/Python/2.7/lib/python/site-packages/pyjs9-1.0-py2.7.egg/pyjs9/__init__.py", line 127, in _im2np
    w = int(im['width'])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

Maybe you could try out this branch and check if Python 2 still works for you?
Unfortunately I'm very busy with work this week, so either you continue with this branch or I'll come back to it next weekend.

File: pyjs9/__init__.py [hunk 2]
```diff
@@ -225,19 +231,21 @@ def send(self, obj, msg='msg'):
...
+            raise IOError("{0}: {1}".format(self.host, e.strerror))
+
         urtn = url.read()
+
         if urtn[0:6] == 'ERROR:':
-            raise ValueError, urtn
+            raise ValueError(urtn)
         try:
-            res = json.loads(urtn, object_hook=_decode_dict)
+            res = json.loads(urtn.decode('utf8'), object_hook=_decode_dict)
```
Comment (cdeil) [inline pyjs9/__init__.py:248]: I'm not sure the UTF8 encode and decode are correct here ... this was just a try to make it work on Python 3.
The problem I have is that I don't have working examples of responses I can check .... if I had that for the `master` branch I could probably make it work for Python 2 and 3 in this branch.

**Comment by ericmandel** [comment]
I may have time to look at this during the week. The problem almost certainly is the change to urllib2. I'm pretty sure I had problems with urllib2 when I wrote the original pyjs9 code, and ended up using urllib. What I'll do is check this by modifying the main branch to use urllib2 -- but I bet it won't work with that change.

Assuming that is the case, there are two options:
1. figure out how to use urllib2
2. use requests 

I'll try to get some time to play with each. In the meantime, let me know your thoughts on switching directly to requests ...

**Comment by taldcroft** [comment]
@ericmandel - many people are using requests now and it seems to be a reasonably light dependence (and easy to bundle).

Having said that, for reference the `six` package provides a compatibility layer .  "The six.moves.urllib package is a version-independent location for this functionality; its structure mimics the structure of the Python 3 urllib package."  Of course then you need to bundle `six`, but that is also easy.  :smile:

**Comment by cdeil** [comment]
+1 to use requests.

@ericmandel – you said that you want to use socket.io 1.0 and haven't found a Python package yet that supports that, so if this is just a temp solution anyways, my suggestion would be to simply `import requests` and declare it as a dependency in `setup.py` (as opposed to bundling all files from `requests` into `pyjs9/extern/requests`)

**Comment by ericmandel** [comment]
OK, that's good enough for me. What I'll do is add support for requests and, once that is done, update the master.  Maybe I'll even get the dependency specification right ... then you can use that to move forward on the python3 support.

I still don't understand why you cannot connect with any back-end helpers, either to port 8080 (mred1.cfa.harvard.edu) or port 2718 (js9.si.edu). If you have 2 minutes, please try the following:
1. visit js9.si.edu in a browser
2. create a circle region from the Region menu
3. click the Analysis tab
4. click Energy Spectrum

Do you get a plot? if so, then the browser connected successfully to the back-end helper and sent a message. No python involved. If not ...

File: setup.py [hunk 3]
```diff
@@ -14,10 +40,15 @@ def readme():
...
         'Topic :: Scientific/Engineering :: Astronomy',
       ],
       keywords='astronomy astrophysics image display',
       url='http://js9.si.edu',
       license='MIT',
-      packages=['pyjs9'],
-      zip_safe=False)
+      packages=['pyjs9', 'pyjs9.extern'],
+      zip_safe=False,
+      tests_require=['pytest', 'selenium'],
```
Comment (cdeil) [inline setup.py:52]: @ericmandel – To declare the dependency on `requests` you should add the following line here:

``` python
install_requires = ['requests']
```

See http://stackoverflow.com/a/15835083/498873

**Comment by cdeil** [comment]
`js9.si.edu` currently doesn't work for me ... I see this error in the network panel (with latest Chrome and Mac OS X)
screen shot 2015-03-03 at 19 16 24

No idea if this is a network or computer or browser issue on my end, or an issue on the server side ...

**Comment by cdeil** [comment]
Here's some more info from the Chrome dev tools:
screen shot 2015-03-03 at 19 20 04

With Firefox it hangs for me at the same position, but doesn't time out even after a minute.

**Comment by ericmandel** [comment]
I restarted the Node server but that won’t help, of course. If your JS9 is not the latest version, you might try emptying your browser cache(s). Chrome in particular is very aggressive about caching javascript.

**Comment by taldcroft** [comment]
FWIW the js9.si.edu site works for me and I got an energy spectrum with no trouble.  (Using chrome on mac from my home network).

**Comment by montefra** [comment]
> Regarding use of urllib (or urllib2): this is a temp solution, because last time I checked, python did not support socket.io 1.x (it had some primitive support for v0.9 at one point)

@ericmandel : now they support [socket.io 1.x](https://pypi.python.org/pypi/socketIO-client)

File: setup.py (hunk 3 above)
Comment (montefra) [inline setup.py:52]: I think that the best would be to add 

```
install_requires = ['requests', 'six']
```

and get rid of `pyjs9/extern` altogether

**Comment by ericmandel** [comment]
@montefra This news is fantastic and important. Once we get the python3 code stabilized, I'll add socket.io as a communication option.

File: setup.py (hunk 3 above)
Comment (cdeil) [inline setup.py:52]: Agree that getting rid of `extern` and just declaring `six` and `requests` as dependencies that will be auto-installed by pip or whatever package manager the user has is the best solution.
I wouldn't have said that a year or two ago, but the Python packaging situation is good by now and keeps getting better ...

**Comment by cdeil** [comment]
@montefra – Can you take this over (or start anew from master)?
If you don't have time, I can have a look at this again and try finishing it to a usable state next week.

**Comment by montefra** [comment]
@cdeil: has you have already seen #5 adds python 3 support.

I can certainly cherrypick some of your commits, travis setup and tests, and adapt them to my implementation.

**Comment by ericmandel** [comment]
This PR was already fixed by @montefra, so I'll close it.
